export enum PATH {
  ARTICULO = 'articulo',
  CONTACTO = 'contacto',
  HOME = '',
  IMAGEN = 'imagen',
  INICIO = 'inicio',
  SOPORTE = 'Soporte',
  PERFIL = 'Perfil',
  PRODUCTOS = 'Productos',
  PEDIDOS = 'Pedidos',
  LOGIN = 'Login',
  ROLES = 'Roles',
  DASHBOARD = 'Dashboard',
  FORGOT = 'Forgot-Password',
  REGISTER = 'Register',
  RESET = 'reset-password',
  EDITAR_PRODUCTO = 'editar-producto/:id',
  VER_ESTADISTICAS = 'producto-estadisticas/:id',
}
