export enum PATH {
  ARTICULO = 'articulo',
  CLIENTES = 'Clientes',
  CONTACTO = 'contacto',
  HOME = '',
  IMAGEN = 'imagen',
  INICIO = 'inicio',
  SOPORTE = 'Soporte',
  PERFIL = 'Perfil',
  PRODUCTOS = 'productos',
  PEDIDOS = 'Pedidos',
  LOGIN = 'Login',
  ROLES = 'Roles',
  DASHBOARD = 'Dashboard',
  FORGOT = 'Forgot-Password',
  REGISTER = 'Register',
  RESET = 'reset-password',
}
